apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mtnx-recharge
  namespace: mtnx-apps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  rules:
    - host:
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mtnx-recharge
                port:
                  number: 8080

    #  curl --resolve "randmeth.portals:80:$( minikube ip )" -i http://randmeth.portals
