apiVersion: v1
kind: Service
metadata:
  name: mtnx-recharge
  namespace: mtnx-apps
spec:
  type: LoadBalancer
  selector:
    app: mtnx-recharge
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 8080
