apiVersion: v1
kind: Service
metadata:
  name: { { include "helm.fullname" . } }
  namespace: mtnx
spec:
  type: { { .Values.service.type } }
  selector:
    app: mtnx-demo
  ports:
    - nodePort: 31479
      port: { { .Values.service.port } }
      targetPort: 8080
