apiVersion: v1
kind: Service
metadata:
  name: mtnx-demo
  namespace: mtnx
spec:
  type: LoadBalancer
  selector:
    app: mtnx-demo
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 8080
