apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform
spec:
  destination:
    name: ''
    namespace: mtnx
    server: 'https://kubernetes.default.svc'
  source:
    path: platform/resources
    repoURL: 'https://github.com/tkhalane/mtnx-demo'
    targetRevision: HEAD
  sources: []
  project: mtnx-platform
