replicaCount: 1
image:
  repository: tkhalane/mtnx-demo
  # repository: randmeth.azurecr.io/spring-boot-starter-parent-campaigns
  pullPolicy: Always
  tag: 66b036498ae8912f9655b92ae75c735e7c4a5537
fullnameOverride: randmeth-campaigns
serviceAccount:
  create: true
  annotations: {}
  name: ''
service:
  type: LoadBalancer
  port: 8080
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
