apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: mtnx-mongo-with-redis
spec:
  compositeTypeRef:
    apiVersion: mtnx.com/v1alpha1
    kind: XMongoWithCache
  resources:
    - name: mongo-db
      base:
        apiVersion: cosmosdb.azure.upbound.io/v1beta1
        kind: MongoDatabase
        metadata:
          labels:
            mtnx.com/nosql-db: mtnid-mongo
          name: mtnx-mongo
        spec:
          forProvider:
            accountName: mtnx-mongo
            resourceGroupName: platform-engineering-sg
    - name: redis-cache
      base:
        apiVersion: cache.azure.upbound.io/v1beta1
        kind: RedisCache
        metadata:
          name: mtnx-cache
        spec:
          forProvider:
            capacity: 1
            enableNonSslPort: false
            family: P
            location: East US
            redisConfiguration:
              - maxmemoryDelta: 2
                maxmemoryPolicy: allkeys-lru
                maxmemoryReserved: 2
            redisVersion: "6"
            resourceGroupName: platform-engineering-sg
            skuName: Premium
      patches:
        - fromFieldPath: "spec.version"
          toFieldPath: "spec.forProvider.redisVersion"
          