name: Build and deploy an app to AKS with Helm

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "randmeth"
  CONTAINER_NAME: "campaigns"
  RESOURCE_GROUP: "platform-engineering-sg"
  IMAGE_TAG: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # client-id: ${{ secrets.AZURE_CLIENT_ID }}
          # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: |
          export CONTAINER_REGISTRY=${{ env.AZURE_CONTAINER_REGISTRY}}
          export IMAGE_TAG=${{ env.IMAGE_TAG }}
          echo 'Install ACR AAD credential helper and login'
           curl -L https://aka.ms/acr/installaad/bash | /bin/bash
           az acr login -n randmeth
           echo 'Start Build'
           mvn compile jib:build
           echo 'Build complete'
        # Replace CONTAINER_REGISTRY & IMAGE_TAG  in all the manifest files
      # - uses: cschleiden/replace-tokens@v1
      #   with:
      #     tokenPrefix: "${"
      #     tokenSuffix: "}"
      #     files: '["helm/values.yaml"]'
      #   env:
      #     CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      #     IMAGE_TAG: ${{ env.IMAGE_TAG }}
      # - name: Checkout main
      #   uses: actions/checkout@v2
      #   with:
      #     repository: github.com/tkhalane/mtnx-demo.git
      #     persist-credentials: false
      #     fetch-depth: 0
      # - name: Update manifests
      #   run: |
      #     sleep 1
      #     git config --global user.name "${{ secrets.GH_ORG }}"
      #     git add .
      #     git commit -m "Promoting devops-toolkit ${{ github.sha }}"
      # - name: Push prod
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GH_TOKEN }}
      #     repository: ${{ secrets.GH_ORG }}/devspace-vcluster-argocd-prod
      - uses: azure/k8s-bake@v2.4
        with:
          renderEngine: "helm"
          helmChart: "./helm/"
          overrideFiles: "./helm/values.yaml"
          overrides: |
            replicaCount:2
          helm-version: "latest"
        id: bake
