name: Build and deploy an app to AKS with Helm

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_CONTAINER_REGISTRY: "randmeth"
  CONTAINER_NAME: "campaigns"
  RESOURCE_GROUP: "platform-engineering-sg"
  IMAGE_TAG: "latest-test"

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     - uses: azure/login@v1
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}
  #         # client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - run: |
  #         export CONTAINER_REGISTRY=${{ env.AZURE_CONTAINER_REGISTRY}}
  #         export IMAGE_TAG=${{ env.IMAGE_TAG }}
  #         echo 'Install ACR AAD credential helper and login'
  #          curl -L https://aka.ms/acr/installaad/bash | /bin/bash
  #          az acr login -n randmeth
  #          echo 'Start Build'
  #          mvn compile jib:build
  #          echo 'Build complete'

  #     - name: Update Helm Values
  #       id: update-helm-values
  #       run: |
  #         sed -i 's|image:.*|image: "your-docker-image:latest"|' helm/values.yaml
  #         yq eval '.image.tag = "${{ env.IMAGE_TAG }}"' -i helm/values.yaml
  #         cat helm/values.yaml

  #     - name: Commit Changes
  #       run: |
  #         echo "${{ github.actor }}"
  #         git config user.name "${{ github.actor }}"
  #         git config user.email "${{ github.actor }}@users.noreply.github.com"
  #         git add helm/values.yaml
  #         git commit -m "Update Docker image in Helm values file"
  #         git push
  update-helm-values:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Helm Chart
        uses: actions/checkout@v3

      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "helm/values.yaml"
          propertyPath: "image.tag"
          value: "${{ env.IMAGE_TAG }}"
          branch: main
          targetBranch: main
          createPR: false
          message: "Update Image Version to ${{ env.IMAGE_TAG }}"
