name: Scaffold new service repository from Cookiecutter

on:
  workflow_dispatch:
    inputs:
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
    secrets:
      ORG_TOKEN:
        required: true
      PORT_CLIENT_ID:
        required: true
      PORT_CLIENT_SECRET:
        required: true
jobs:
  scaffold:
    runs-on: ubuntu-latest
    steps:
      - name: Add log to Port action
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          operation: PATCH_RUN
          runId: ${{ fromJson(inputs.port_payload).context.runId }}
          logMessage: "Scaffolding a new repository from Cookiecutter template 🏃‍♂️"
      - uses: tkhalane/cookiecutter-gha@v8
        with:
          portClientId: ${{ secrets.PORT_CLIENT_ID }}
          portClientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          token: ${{ secrets.ORG_TOKEN }}
          portRunId: ${{ fromJson(inputs.port_payload).context.runId }}
          repositoryName: ${{ fromJson(inputs.port_payload).payload.properties.name }}
          portUserInputs: ${{ toJson(fromJson(inputs.port_payload).payload.properties.options) }}
          #   cookiecutterTemplate: ${{ fromJson(inputs.port_payload).payload.properties.template }}
          cookiecutterTemplate: https://github.com/tkhalane/cookiecutter-springboot
          blueprintIdentifier: "microservice"
          organizationName: tkhalane

          # - scaffold repo, push to it github
          # - create helm repo for the new project
          #   - replace all template and values with input from user, set hardcoded namespace
          #   - commit and push helm chart
          # - create ArgoCD application
          #   - source is the helm chart of the new guy
          # - trigger a docker image build for the new created repo.
          #   - It has a docker file. Do we build normal or with JIB?
          #   - update helm chart with new build tag
          # - argo cd should trigger a deployment
